# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tazer/v1/daemon_control.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tazer/v1/daemon_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tazer.v1 import common_pb2 as tazer_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtazer/v1/daemon_control.proto\x12\x08tazer.v1\x1a\x15tazer/v1/common.proto\"\x10\n\x0eVersionRequest\"C\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\r\n\x05\x62uild\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\"\x9d\x01\n\x11\x43\x61pabilityPayload\x12\x16\n\x0eprotocol_major\x18\x01 \x01(\r\x12\x16\n\x0eprotocol_minor\x18\x02 \x01(\r\x12\x12\n\noperations\x18\x03 \x03(\r\x12/\n\x11max_payload_sizes\x18\x04 \x03(\x0b\x32\x14.tazer.v1.UInt32Pair\x12\x13\n\x0b\x63ompression\x18\x05 \x03(\t\"\'\n\x17\x43onfigurationGetRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\">\n\x18\x43onfigurationGetResponse\x12\"\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\x12.tazer.v1.KeyValue\"@\n\x1a\x43onfigurationUpdateRequest\x12\"\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\x12.tazer.v1.KeyValue\"*\n\x0bRejectedKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"W\n\x1b\x43onfigurationUpdateResponse\x12\x0f\n\x07\x61pplied\x18\x01 \x03(\t\x12\'\n\x08rejected\x18\x02 \x03(\x0b\x32\x15.tazer.v1.RejectedKey\"\"\n\x0eRestartRequest\x12\x10\n\x08\x64\x65lay_ms\x18\x01 \x01(\r\"C\n\x0fRestartResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x1a\n\x12\x65\x66\x66\x65\x63tive_delay_ms\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tazer.v1.daemon_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONREQUEST']._serialized_start=66
  _globals['_VERSIONREQUEST']._serialized_end=82
  _globals['_VERSIONRESPONSE']._serialized_start=84
  _globals['_VERSIONRESPONSE']._serialized_end=151
  _globals['_CAPABILITYPAYLOAD']._serialized_start=154
  _globals['_CAPABILITYPAYLOAD']._serialized_end=311
  _globals['_CONFIGURATIONGETREQUEST']._serialized_start=313
  _globals['_CONFIGURATIONGETREQUEST']._serialized_end=352
  _globals['_CONFIGURATIONGETRESPONSE']._serialized_start=354
  _globals['_CONFIGURATIONGETRESPONSE']._serialized_end=416
  _globals['_CONFIGURATIONUPDATEREQUEST']._serialized_start=418
  _globals['_CONFIGURATIONUPDATEREQUEST']._serialized_end=482
  _globals['_REJECTEDKEY']._serialized_start=484
  _globals['_REJECTEDKEY']._serialized_end=526
  _globals['_CONFIGURATIONUPDATERESPONSE']._serialized_start=528
  _globals['_CONFIGURATIONUPDATERESPONSE']._serialized_end=615
  _globals['_RESTARTREQUEST']._serialized_start=617
  _globals['_RESTARTREQUEST']._serialized_end=651
  _globals['_RESTARTRESPONSE']._serialized_start=653
  _globals['_RESTARTRESPONSE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
