# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tazer/v1/process.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tazer/v1/process.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tazer/v1/process.proto\x12\x08tazer.v1\"p\n\x0bProcessInfo\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x04 \x01(\x02\x12\x14\n\x0cmemory_bytes\x18\x05 \x01(\x04\x12\r\n\x05state\x18\x06 \x01(\t\"$\n\x12ProcessListRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"?\n\x13ProcessListResponse\x12(\n\tprocesses\x18\x01 \x03(\x0b\x32\x15.tazer.v1.ProcessInfo\"1\n\x12ProcessKillRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x0e\n\x06signal\x18\x02 \x01(\x05\"&\n\x13ProcessKillResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x12ProcessInfoRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\"x\n\x13ProcessInfoResponse\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.tazer.v1.ProcessInfo\x12\x14\n\x0c\x63ommand_line\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x04\x12\x12\n\nopen_files\x18\x04 \x03(\t\"9\n\x15ProcessMonitorRequest\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x13\n\x0binterval_ms\x18\x02 \x01(\r\"\x89\x01\n\x16ProcessMonitorResponse\x12#\n\x04info\x18\x01 \x01(\x0b\x32\x15.tazer.v1.ProcessInfo\x12\x0e\n\x06\x65xited\x18\x02 \x01(\x08\x12\x11\n\texit_code\x18\x03 \x01(\x05\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x17\n\x0f\x65xit_code_known\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tazer.v1.process_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSINFO']._serialized_start=36
  _globals['_PROCESSINFO']._serialized_end=148
  _globals['_PROCESSLISTREQUEST']._serialized_start=150
  _globals['_PROCESSLISTREQUEST']._serialized_end=186
  _globals['_PROCESSLISTRESPONSE']._serialized_start=188
  _globals['_PROCESSLISTRESPONSE']._serialized_end=251
  _globals['_PROCESSKILLREQUEST']._serialized_start=253
  _globals['_PROCESSKILLREQUEST']._serialized_end=302
  _globals['_PROCESSKILLRESPONSE']._serialized_start=304
  _globals['_PROCESSKILLRESPONSE']._serialized_end=342
  _globals['_PROCESSINFOREQUEST']._serialized_start=344
  _globals['_PROCESSINFOREQUEST']._serialized_end=377
  _globals['_PROCESSINFORESPONSE']._serialized_start=379
  _globals['_PROCESSINFORESPONSE']._serialized_end=499
  _globals['_PROCESSMONITORREQUEST']._serialized_start=501
  _globals['_PROCESSMONITORREQUEST']._serialized_end=558
  _globals['_PROCESSMONITORRESPONSE']._serialized_start=561
  _globals['_PROCESSMONITORRESPONSE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
